# Server Configuration
server.port=8080
spring.main.allow-circular-references=true

#
spring.datasource.url=jdbc:postgresql://aws-0-eu-north-1.pooler.supabase.com:6543/postgres?user=postgres.uahsvmkrnseeosoxbgrc&password=bcGvyzziEpWH5fPV
spring.datasource.username=postgres
spring.datasource.password=bcGvyzziEpWH5fPV
spring.jpa.hibernate.ddl-auto=none
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
spring.datasource.hikari.data-source-properties.preparedStatementCacheQueries=256
spring.datasource.hikari.maximum-pool-size=5
spring.datasource.hikari.minimum-idle=2
spring.h2.console.enabled=false

# JWT Configuration
jwt.secret=a5f9b3e1c8d7e0f2a9b3c4d5e6f7g8h9i0j1k2l3m4n5o6p7q8r9s0t1u2v3w4x5y6z7
jwt.expiration.ms=86400000

# FastAPI AI Service Configuration
hypatia.ai.fastapi.url=https://lilianaca94-hypatia-maola.hf.space/analizar
hypatia.ai.fastapi.analyze-path=/api/analizar
hypatia.ai.request-timeout-seconds=30